### ISSUE TITLE
Versions 1.1.3 and 1.1.4: Error loading "word-wrap"

### ISSUE THREAD

**Issue by JamieMason** [commitizen/cz-conventional-changelog#9]
Since upgrading to 1.1.4 this morning I get the following error. 

```bash
$ git-cz
Potentially unhandled rejection [3] Error: Error loading "word-wrap" at file:/path/to/my/project/node_modules/cz-conventional-changelog/word-wrap.js
Error loading "word-wrap" from "index" at file:/path/to/my/project/node_modules/cz-conventional-changelog/index.js
ENOENT, open '/path/to/my/project/node_modules/cz-conventional-changelog/word-wrap.js'
    at Error (native)
```

(I realise this report is quite brief, but I'm not sure what else to add. Please ask for any more info you need and I'll get it for you).

Thanks a lot for this great tool.

**Comment by JamieMason** [comment]
Issue still happens when downgrading to 1.1.3, but 1.1.2 is fine.

**Comment by jimthedev** [comment]
Thanks for letting me know. There are some issues right now with the cli/adapter and all of the possible node/npm combos so it is tricky locking down what combos are working and which aren't. I'm building a comprehensive test suite to track this and also a cli command so that you can just type `commitizen up` or something like that and it will check to make sure you have the most recent version of everything. It is taking some time but I think it will be worth it in the long run. 

Let this be a lesson. Write tests early, even if you're the only one you think will ever use your software :D

**Comment by JamieMason** [comment]
I've definitely been burnt by that before too, good luck :)

**Comment by jimthedev** [comment]
Thanks. I'll post here when this is fixed and mention you.
